### PR TITLE
Polygonal multilayer

### PR DESCRIPTION
**Pull request by Justinfront**
Azrafe7 I think this fixes the main issue with this example do you think this is ok to merge now or should I work on looks or any bugs you see?  Seems a shame to loose the castle but atleast goes back to MIT fully.  I was not sure how to setup gitnore to allow some examples can you advise?  Feel free if you think it's ok to merge and then tweak structures.

### CODE REVIEW

**Comment by Justinfront** [comment]
I was thinking of maybe moving more out of main maybe the find stuff into the iterator class but really I am wondering this blend of projects is too useful and should be more integrated into core, maybe after making it possible to have sub polygonal graphs as well?

**Comment by Justinfront** [comment]
the "internal" should allow some simplification of the remove dynamic nodes and allow the use of only one array at moment it turned out not of any extra help for the new clean method.

**Comment by azrafe7** [comment]
For me it's OK to merge this. Nice job!

I'm not experiencing any bugs so far, it seems to always find the correct path.

Random thoughts:
- cpp/neko: after going around a bit the FPS drops significantly (but it's a general issue - not bound to this demo only -)
- agree on trying to simplify the Main (currently can seem quite difficult to setup layers and portals from a newbie user POV)
- the FlashDevelop project file (.hxproj) is now missing, we might want to re-add it (also there's a typo in the folder name, but both issues are easiliy fixed!)
- haven't yet tested it, but I'm wondering if the current impl. supports portals with both endpoints on the same layer

About .gitignore and examples:
due to openfl folder namings it's not easily possible to setup .gitignore in a way to include some files in the bin folders and skip others (this is mainly because there's `bin/*/bin` etc. - I've tried to work around that but had no success). What I did lately was to modify my _local_ .gitignore, and then push only the needed output files (watching out to not push .gitignore itself).

**Comment by Justinfront** [comment]
any chance you can fix these, mod the readme with the new links?  I can look tomorrow but won't tonight.

**Comment by azrafe7** [comment]
Sure. Wait a min (won't include the android one though - too big)...

2015-02-12 1:48 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
Yep it supports end points on the same layer.  The start end points are portals added dynamically specifcially this line optimizes the A\* for this situation. 
https://github.com/Justinfront/hxDaedalus-NME-OpenFL-Examples/blob/master/hxDaedalus-NME-OpenFL-Examples/06-Mutlilayer/src/RenderPathIterator.hx#L32

**Comment by Justinfront** [comment]
the 'clean' function removes multiple portals from the A\* on a single mesh because it is assumed that a mesh path would be shorter and seems it is, that was the main bug.  So had to look at repeats within layer after the first point and from the other side at the end and then multiple points on a between mesh, the algorithm I came up with seems to work but not highly tested just logic so hopefully I got it right :)

**Comment by Justinfront** [comment]
the main feed back I have had is that users can't tell how to click on a non hit area I was not sure if we can fill them easy thought maybe another image would be better.

**Comment by Justinfront** [comment]
Android might be good for show and tell at work but I don't want github telling me I have no room left.

**Comment by Justinfront** [comment]
I am thinking movement is next thing to tackle, are you interested to explore this? It would be nice to do a hxDaedalus and Nape mash up. I don't know nape yet so might be more inclinded to try physaxe as it seems simpler.

**Comment by azrafe7** [comment]
Well.. it's taking more than expected, but I'm almost there!

2015-02-12 2:03 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
I'm sorry I don't know the time there but if it's getting too late then it can wait, no urgency.

**Comment by azrafe7** [comment]
No worries... Done!

(there's also an apk, but I haven't tested it)

2015-02-12 2:28 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
Brilliant :) I will try the apk at work I have blue stacks installed but not on the mac.

**Comment by azrafe7** [comment]
OK. Let me know how it goes!

2015-02-12 2:35 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
I think there is a problem... only the examples are in the repository not the code?

**Comment by azrafe7** [comment]
Shit!!!

Sorry, I'll fix it ASAP.

2015-02-12 2:44 GMT+01:00 Justinfront notifications@github.com:

**Comment by azrafe7** [comment]
That's because I renamed the folder and things got lost in the process.
Going to fix it right away.

2015-02-12 2:46 GMT+01:00 azrafe7 azrafe7@gmail.com:

**Comment by Justinfront** [comment]
is it best to revert and recommit the bin stuff?

**Comment by Justinfront** [comment]
so the code has history

**Comment by azrafe7** [comment]
Yeah, I'm on it. Sorry

2015-02-12 2:49 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
no worries that's what git is for :)

**Comment by azrafe7** [comment]
Only not that much intuitive when it comes to fixing these type of
mistakes. ;D

2015-02-12 2:52 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
if you can revert we can leave the rest till later

**Comment by Justinfront** [comment]
or we can take a look tomorrow evening?  Don't feel it has to be fixed right now.

**Comment by azrafe7** [comment]
I'll be up for another hour at least. I'm confident I'll fix it by
rewriting history and reapplying the bin files. All should be good by
tomorrow morning. Wish me good luck. ;)

2015-02-12 3:02 GMT+01:00 Justinfront notifications@github.com:

**Comment by Justinfront** [comment]
well if you get too tired there is no deadline the code is all there just not how we want it so it can wait, but good luck, I need to get to sleep I would offer to help but suspect my git is pretty bad.

**Comment by azrafe7** [comment]
Oh, don't worry, really. That's fun for me... I'm getting some more git
knowledge. I'll get back to you tomorrow (with good news!).

'night Justin!

2015-02-12 3:09 GMT+01:00 Justinfront notifications@github.com:

**Comment by azrafe7** [comment]
Phew... Hope it's all in place now.

2015-02-12 3:15 GMT+01:00 azrafe7 azrafe7@gmail.com:

**Comment by azrafe7** [comment]
Please let me know if I missed something.

PS: Adding to the 1st entry of my random thoughts above... the user could wrongly assume that the slowdown it's due to the pathfinding algo (which is instead totally bounded by rendering issues - as one can test by switching off paths/entities drawing). So I think it would be an important thing to improve and/or make it clear in the docs/comments.

**Comment by Justinfront** [comment]
I cloned fresh here and compiled flash version fine.  I am unsure what the render issue is but I can take a look but maybe it will depend on the exact use case beyond an example.

**Comment by Justinfront** [comment]
maybe it just needs blitting?

**Pull request merged**
